name: projeto_final
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  mask: ^1.0.3
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  visibility_detector: ^0.3.3
  widget_mask: ^1.0.0+0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/backgroundPage.png
    - assets/images/Vector1.svg
    - assets/images/VectorApp.svg
    - assets/images/Vector.png
    - assets/images/las.svg
    - assets/images/profileMask.png
    - assets/images/teste.jpg
    - assets/images/Vector1.png
    - assets/images/festa.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
